Student_age=c(22,24,25,26,21,21)
print(Student_age)
plot(Student_age,type='l')
plot(Student_age,type='l',main="SIOM's Students Age")
plot(Student_age,type='l',main="SIOM's Students Age",xlab="No of Students",ylab="Students Age")
plot(Student_age,type='l',main="SIOM's Students Age",xlab="No of Students",ylab="Students Age",col=c("red"))
pie(Student_age,type='l',main="SIOM's Students Age",xlab="No of Students",ylab="Students Age",col=c("red"))XXXX
pie(Student_age,main="SIOM's Students Age",xlab="No of Students",ylab="Students Age",col=c("red"))
pie(Student_age,main="SIOM's Students Age",xlab="No of Students",ylab="Students Age",col=c("Green"))
barplot(Student_age,main="SIOM's Students Age",xlab="No of Students",ylab="Students Age",col=c("Green"))
barplot(Student_age,main="SIOM's Students Age",xlab="No of Students",ylab="Students Age",col=c("Green","Red","Blue","Black","Pink","Yellow"))
hist(Student_age,main="SIOM's Students Age",xlab="No of Students",ylab="Students Age",col=c("Green","Red","Blue","Black","Pink","Yellow"))
dotchart(Student_age,main="SIOM's Students Age",xlab="No of Students",ylab="Students Age",col=c("Green","Red","Blue","Black","Pink","Yellow"))
plot(Student_age,type='l',main="SIOM's Students Age",xlab="No of Students",ylab="Students Age",col=c("Green","Red","Blue","Black","Pink","Yellow"))
polygon(Student_age,main="SIOM's Students Age",xlab="No of Students",ylab="Students Age",col=c("Green","Red","Blue","Black","Pink","Yellow"))
install.packages("readxl")

